/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 JarCookie.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei/native";
import { GLTF } from "three-stdlib";
import JarCookie from "@/assets/models/cookies/JarCookie.glb";

type GLTFResult = GLTF & {
  nodes: {
    Lid_Jar_0: THREE.Mesh;
    Lid_Woodgrain_V1_0: THREE.Mesh;
    Cookie_Jar_V8_Jar_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshBasicMaterial;
    Woodgrain_V1: THREE.MeshBasicMaterial;
  };
};

export function Jar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(JarCookie) as GLTFResult;

  return (
    <group {...props} dispose={null} scale={0.055}>
      <mesh
        geometry={nodes.Cookie_Jar_V8_Jar_0.geometry}
        material={materials.material}
        position={[130.539, 12.147, -12]}
      >
        <meshStandardMaterial transparent color={"#FFFFFF"} opacity={0.45} />
      </mesh>

      <mesh
        geometry={nodes.Lid_Jar_0.geometry}
        material={materials.material}
        position={[130.539, 26.404, -12]}
      />
      <mesh
        geometry={nodes.Lid_Woodgrain_V1_0.geometry}
        material={materials.Woodgrain_V1}
        position={[130.538, 31.335, -12]}
      />
    </group>
  );
}

useGLTF.preload(JarCookie);
